# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad7ca170d684a115b75184f69ba03507632a640dc1236dccca8f1999ed04193595e7b8f921b3d49a05aadfb8cba131391ac3e420c5951ec6d1b43019f3add814

test:
  secret_key_base: 6176dd024dce8ab043d8f7e25d34e24c4c151fd5eb64142a9d211a5bff6ac2f96f3e2a491a6dba151b8c66bc169aa2c9c2e7406a3c3028d3c723a0d7edc09f8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
